main:
	~/msvc/bin/x86/msbuild.exe "C:\Program Files (x86)\SporeModder FX\Spore ModAPI\Spore ModAPI\Spore ModAPI.vcxproj" -p:Configuration=Release;Platform=Win32
	~/msvc/bin/x86/msbuild.exe "Spore-AdvancedCE.vcxproj" /p:Configuration=Release
